name: Train DDPG Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [1, 2, 3, 4]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python train.py --output-dir output

      - name: Zip output directory
        run: |
          zip -r model_${{ matrix.runner }}_artifacts.zip output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model_${{ matrix.runner }}_artifacts
          path: model_${{ matrix.runner }}_artifacts.zip
          retention-days: 1