[tool.poetry]
name = "microevolution"
version = "0.1.0"
description = "Microevolution project"
authors = [
    { name = "Artsiom Rachok", email = "artemgsr@gmail.com" }
]
readme = "README.md"
packages = [
    { include = "client" },
    { include = "server" }
]
requires-python = ">=3.12"

[tool.poetry.dependencies]
python = ">=3.12"
numpy = ">=2.2.5,<3.0.0"
torch = ">=2.7.0,<3.0.0"

[tool.poetry.group.client.dependencies]
pygame = ">=2.6.1,<3.0.0"
pygame-menu = ">=4.5.2,<5.0.0"
matplotlib = ">=3.10.3,<4.0.0"

[tool.poetry.group.server.dependencies]
matplotlib = ">=3.10.3,<4.0.0"
flask = ">=3.1.0,<4.0.0"
flask-socketio = ">=5.5.1,<6.0.0"
werkzeug = ">=3.1.3,<4.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
