DISH_RADIUS: 350
DISH_COLLISION_PENALTY: -15
DISH_PENALTY_MAX: -30

OBSTACLE_RADIUS: 10
OBSTACLE_COLLISION_PENALTY: -30
OBSTACLE_SPEED: 1
OBSTACLE_QUANTITY: 30

FOOD_RADIUS: 5
FOOD_ENERGY: 5
FOOD_REWARD: 20
FOOD_QUANTITY: 60

ORGANISM_RADIUS: 15
ORGANISM_SPEED: 1.5
ORGANISM_INITIAL_ENERGY: 10
ORGANISM_ENERGY_LOSS_RATE: 0.02
ORGANISM_SPEED_ENERGY_LOSS_MULTIPLIER: 0.001
ORGANISM_ENERGY_DEPLETION_PENALTY: -10
ORGANISM_COLOR: BLUE
ORGANISM_COLOR2: ORANGE