DISH_RADIUS: 350
DISH_COLLISION_PENALTY: -15
DISH_PENALTY_MAX: -30

OBSTACLE_RADIUS: 10
OBSTACLE_COLLISION_PENALTY: -30
OBSTACLE_SPEED: 1
OBSTACLE_QUANTITY: 30

FOOD_RADIUS: 5
FOOD_ENERGY: 5
FOOD_REWARD: 20
FOOD_QUANTITY: 60

ORGANISM_RADIUS: 15
ORGANISM_SPEED: 1.5
ORGANISM_INITIAL_ENERGY: 10
ORGANISM_ENERGY_LOSS_RATE: 0.02
ORGANISM_SPEED_ENERGY_LOSS_MULTIPLIER: 0.001
ORGANISM_ENERGY_DEPLETION_PENALTY: -10
ORGANISM_COLOR: BLUE
ORGANISM_COLOR2: ORANGE

# Параметры обучения
LEARNING_RATE: 0.0001
EPSILON: 0.1  # Для epsilon-greedy стратегии
GAMMA: 0.99  # Фактор дисконтирования
TAU: 0.005  # Скорость копирования весов основной сети в target сеть
BATCH_SIZE: 80
